version: '3.8'

services:
  clustered-data-warehouse-db:
    image: postgres:13
    container_name: warehouse-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  clustered-data-warehouse-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clustered-data-warehouse-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://clustered-data-warehouse-db:5432/warehouse
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user123
    depends_on:
      - clustered-data-warehouse-db
    ports:
      - "8080:8080"

volumes:
  pgdata:
